#!/bin/sh
echo "data appended first time" 
echo "this echo is 2nd time" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 
echo "testing appending data" 